name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: change UseImGui to false
      run: for FILENAME in $(find -name "Directory.Build.props"); do sed -i 's/<UseImGui>true/<UseImGui>false/g' $FILENAME; done
    - name: Restore dependencies
      working-directory: pTyping
      run: dotnet restore
    - name: Build
      working-directory: pTyping
      run: dotnet build --no-restore
    - name: Test
      working-directory: pTyping
      run: dotnet test --no-build --verbosity normal
    - name: Package AppImage
      working-directory: pTyping
      run: ../build-tools/publish-appimage/publish-appimage -y
