name: Run Tests
on:
  push:
jobs:
  publish:
    name: Build, Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository with submodules
        uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Run Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          # project_path: tests/My.Project.Tests
          report_name: ptyping_tests
          report_title: pTyping Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
